import type { Metadata } from 'next';

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || 'https://travel-taste.example.com';
const SITE_NAME = 'Travel Taste';
const TITLE = 'Travel Taste — A Private Diary';
const DESCRIPTION =
  'A small letterbox of postcards from the road, kept for the people who matter. Invite-only travel and food diary, broadcast to a hand-picked circle.';

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: TITLE,
    template: '%s · Travel Taste',
  },
  description: DESCRIPTION,
  applicationName: SITE_NAME,
  authors: [{ name: SITE_NAME }],
  generator: 'Next.js',
  keywords: [
    'private photo diary',
    'invite-only photo sharing',
    'travel journal',
    'private instagram alternative',
    'passcode photo gallery',
  ],
  category: 'lifestyle',
  alternates: {
    canonical: '/',
  },
  openGraph: {
    type: 'website',
    siteName: SITE_NAME,
    title: TITLE,
    description: DESCRIPTION,
    url: SITE_URL,
    locale: 'en_US',
  },
  twitter: {
    card: 'summary_large_image',
    title: TITLE,
    description: DESCRIPTION,
  },
  robots: {
    index: true,
    follow: false, // landing is the only thing crawlers should see
    nocache: true,
    googleBot: {
      index: true,
      follow: false,
      'max-snippet': 160,
      'max-image-preview': 'standard',
      'max-video-preview': 0,
    },
  },
  // Icons are generated by app/icon.tsx and app/apple-icon.tsx (Next conv).
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  other: {
    'theme-color': '#f4ead7',
  },
};

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#f4ead7' },
    { media: '(prefers-color-scheme: dark)', color: '#14181f' },
  ],
};
